USE PetCareDB
GO

SELECT * FROM THUOC

SELECT * FROM KHACHHANG

SELECT * FROM TAIKHOAN


SELECT * FROM NHANVIEN

SELECT * FROM DANHGIA

SELECT * FROM TAIKHOAN
WHERE LoaiTK = N'Quản lý chi nhánh'

SELECT * FROM KHACHHANG AS NV, TAIKHOAN AS TK
WHERE TK.ID_TK = NV.ID_TK

SELECT * FROM NHANVIEN AS NV, TAIKHOAN AS TK
WHERE NV.ChiNhanhLamViec = 'CN06' AND TK.ID_TK = NV.ID_TK AND NV.ChucVu = N'Bác sĩ'

SELECT * FROM LS_DVKHAMBENH

SELECT * FROM LS_DVMUAHANG

SELECT * FROM LS_DV

SELECT * FROM LS_DVTIEMPHONG

SELECT * FROM DICHVU

SELECT* FROM THUCUNG

SELECT * FROM CT_HOADON

SELECT* FROM LS_DANGKY

SELECT * FROM GOITIEM

SELECT* FROM LS_DANGKY

SELECT * FROM HOADON
ORDER BY NV_Lap

SELECT * FROM CT_KHUYENMAI

SELECT * FROM CHINHANH
 
SELECT * FROM CT_SPCN
WHERE MaCN = 'CN08' 

SELECT * FROM SANPHAM

SELECT * FROM VACXIN

SELECT* FROM CHINHANH_DV

SELECT MaLSDV, MaKH, MaDichVu, TrangThaiGD 
FROM LS_DV 
WHERE TrangThaiGD = N'Đã đặt trước'

UPDATE NHANVIEN
SET TrangThaiNV = N'Rảnh'
WHERE HoTenNV = N'Bùi Anh Quỳnh' AND ChiNhanhLamViec = 'CN07' AND ChucVu = N'Bác sĩ' 