USE PetCareDB
GO
-- Xóa dữ liệu cũ để tránh trùng lặp nếu chạy lại
DELETE FROM KHUYENMAI;
INSERT INTO KHUYENMAI (MaKM, LoaiKM, GiaKM) VALUES (N'KM001', N'HVCoBan', 3);
INSERT INTO KHUYENMAI (MaKM, LoaiKM, GiaKM) VALUES (N'KM002', N'HVThanThiet', 5);
INSERT INTO KHUYENMAI (MaKM, LoaiKM, GiaKM) VALUES (N'KM003', N'HVVIP', 10);
INSERT INTO KHUYENMAI (MaKM, LoaiKM, GiaKM) VALUES (N'KM004', N'Loyalty', 1000);
